Location.create!([
  {city: "Abu Dhabi", country: "United Arab Emirates", state: nil},
  {city: "Aix-En-Provence", country: "France", state: nil},
  {city: "Alicante", country: "Spain", state: nil},
  {city: "Amsterdam", country: "Netherlands", state: nil},
  {city: "Athens", country: "Greece", state: nil},
  {city: "Atlanta", country: "USA", state: "Georgia"},
  {city: "Atlantic City", country: "USA", state: "New Jersey"},
  {city: "Austin", country: "USA", state: "Texas"},
  {city: "Baltimore", country: "USA", state: "Maryland"},
  {city: "Bangkok", country: "Thailand", state: nil},
  {city: "Barcelona", country: "Spain", state: nil},
  {city: "Beijing", country: "China", state: nil},
  {city: "Benidorm", country: "Spain", state: nil},
  {city: "Bergen", country: "Norway", state: nil},
  {city: "Berlin", country: "Germany", state: nil},
  {city: "Birmingham", country: "England", state: nil},
  {city: "Bologna", country: "Italy", state: nil},
  {city: "Boston", country: "USA", state: "Massachusetts"},
  {city: "Brisbane", country: "Australia", state: "Queensland"},
  {city: "Brussels", country: "Belgium", state: nil},
  {city: "Budapest", country: "Hungary", state: nil},
  {city: "Buenos Aires", country: "Argentina", state: nil},
  {city: "Cairo", country: "Egypt", state: nil},
  {city: "Cannes", country: "France", state: nil},
  {city: "Cape Town", country: "South Africa", state: nil},
  {city: "Chicago", country: "USA", state: "Illinois"},
  {city: "Cologne", country: "Germany", state: nil},
  {city: "Copenhagen", country: "Denmark", state: nil},
  {city: "Dallas", country: "USA", state: "Texas"},
  {city: "Denver", country: "USA", state: "Colorado"},
  {city: "Detroit", country: "USA", state: "Michigan"},
  {city: "Dresden", country: "Germany", state: nil},
  {city: "Dubai", country: "United Arab Emirates", state: nil},
  {city: "Dublin", country: "Ireland", state: nil},
  {city: "Dubrovnik", country: "Croatia", state: nil},
  {city: "Düsseldorf", country: "Germany", state: nil},
  {city: "Edinburgh", country: "Scotland", state: nil},
  {city: "Florence", country: "Italy", state: nil},
  {city: "Fort Lauderdale", country: "US", state: "Florida"},
  {city: "Frankfurt", country: "Germany", state: nil},
  {city: "Fuerteventura", country: "Spain", state: nil},
  {city: "Geneva", country: "Switzerland", state: nil},
  {city: "Glasgow", country: "Scotland", state: ""},
  {city: "Gothenburg", country: "Sweden", state: nil},
  {city: "Gran Canaria", country: "Spain", state: nil},
  {city: "Granada", country: "Spain", state: nil},
  {city: "Hamburg", country: "Germany", state: nil},
  {city: "Hanoi", country: "Vietnam", state: nil},
  {city: "Havana", country: "Cuba", state: nil},
  {city: "Helsinki", country: "Finland", state: nil},
  {city: "Hong Kong", country: "China", state: nil},
  {city: "Honolulu", country: "USA", state: "Hawaii"},
  {city: "Houston", country: "USA", state: "Texas"},
  {city: "Indianapolis", country: "USA", state: "Indiana"},
  {city: "Istanbul", country: "Turkey", state: nil},
  {city: "Kansas City", country: "USA", state: "Kansas"},
  {city: "Krakow", country: "Poland", state: nil},
  {city: "Kuala Lumpur", country: "Malaysia", state: nil},
  {city: "Kyoto", country: "Japan", state: nil},
  {city: "Lake Tahoe", country: "USA", state: "California"},
  {city: "Lanzarote", country: "Spain", state: nil},
  {city: "Las Vegas", country: "USA", state: "Nevada"},
  {city: "Leipzig", country: "Germany", state: nil},
  {city: "Lisbon", country: "Portugal", state: nil},
  {city: "Liverpool", country: "England", state: nil},
  {city: "London", country: "England", state: nil},
  {city: "Los Angeles", country: "US", state: "California"},
  {city: "Lyon", country: "France", state: nil},
  {city: "Madrid", country: "Spain", state: nil},
  {city: "Málaga", country: "Spain", state: nil},
  {city: "Malmo", country: "Sweden", state: nil},
  {city: "Manchester", country: "England", state: nil},
  {city: "Marbella", country: "Spain", state: nil},
  {city: "Marrakech", country: "Morocco", state: nil},
  {city: "Marseille", country: "France", state: nil},
  {city: "Melbourne", country: "Australia", state: "Victoria"},
  {city: "Messina", country: "Italy", state: nil},
  {city: "Mexico City", country: "Mexico", state: nil},
  {city: "Miami", country: "USA", state: "Florida"},
  {city: "Milan", country: "Italy", state: nil},
  {city: "Minneapolis", country: "USA", state: "Minnesota"},
  {city: "Monte Carlo", country: "Monaco", state: nil},
  {city: "Montreal", country: "Canada", state: "Quebec"},
  {city: "Moscow", country: "Russia", state: nil},
  {city: "Mumbai", country: "India", state: nil},
  {city: "Munich", country: "Germany", state: nil},
  {city: "Napa Valley", country: "USA", state: "California"},
  {city: "Naples", country: "Italy", state: nil},
  {city: "Nashville", country: "USA", state: "Tennessee"},
  {city: "New Orleans", country: "USA", state: "Louisiana"},
  {city: "New York", country: "USA", state: "New York"},
  {city: "Nice", country: "France", state: nil},
  {city: "Oakland", country: "USA", state: "California"},
  {city: "Orlando", country: "USA", state: "Florida"},
  {city: "Oslo", country: "Norway", state: nil},
  {city: "Palermo", country: "Italy", state: nil},
  {city: "Paris", country: "France", state: nil},
  {city: "Parma", country: "Italy", state: nil},
  {city: "Philadelphia", country: "USA", state: "Pennsylvania"},
  {city: "Phoenix", country: "USA", state: "Arizona"},
  {city: "Pisa", country: "Italy", state: nil},
  {city: "Portland", country: "USA", state: "Oregon"},
  {city: "Prague", country: "Czech Republic", state: nil},
  {city: "Reykjavik", country: "Iceland", state: nil},
  {city: "Riga", country: "Latvia", state: nil},
  {city: "Rio de Janeiro", country: "Brazil", state: nil},
  {city: "Rome", country: "Italy", state: nil},
  {city: "Sacramento", country: "USA", state: "California"},
  {city: "Salt Lake City", country: "USA", state: "Utah"},
  {city: "Salzburg", country: "Austria", state: nil},
  {city: "San Antonio", country: "USA", state: "Texas"},
  {city: "San Diego", country: "USA", state: "California"},
  {city: "San Francisco", country: "USA", state: "California"},
  {city: "San Jose", country: "USA", state: "California"},
  {city: "San Sebastián", country: "Spain", state: nil},
  {city: "Santa Barbara", country: "USA", state: "California"},
  {city: "São Paulo", country: "Brazil", state: nil},
  {city: "Sardinia", country: "Italy", state: nil},
  {city: "Savannah", country: "USA", state: "Georgia"},
  {city: "Seattle", country: "USA", state: "Washington"},
  {city: "Seoul", country: "Korea", state: nil},
  {city: "Seville", country: "Spain", state: nil},
  {city: "Shanghai", country: "China", state: nil},
  {city: "Siena", country: "Italy", state: nil},
  {city: "Siracusa", country: "Rome", state: nil},
  {city: "Sochi", country: "Russia", state: nil},
  {city: "St. Louis", country: "USA", state: "Missouri"},
  {city: "St. Petersburg", country: "Russia", state: nil},
  {city: "Stockholm", country: "Sweden", state: nil},
  {city: "Stuttgart", country: "Germany", state: nil},
  {city: "Sydney", country: "Australia", state: "New South Wales"},
  {city: "Tallinn", country: "Estonia", state: nil},
  {city: "Tampa", country: "USA", state: "Florida"},
  {city: "Tenerife", country: "Spain", state: nil},
  {city: "Tokyo", country: "Japan", state: nil},
  {city: "Toronto", country: "Canada", state: "Ontario"},
  {city: "Turin", country: "Italy", state: nil},
  {city: "Valencia", country: "Spain", state: nil},
  {city: "Vancouver", country: "Canada", state: "British Columbia"},
  {city: "Venice", country: "Italy", state: nil},
  {city: "Verona", country: "Italy", state: nil},
  {city: "Vienna", country: "Austria", state: nil},
  {city: "Warsaw", country: "Poland", state: nil},
  {city: "Washington DC", country: "US", state: nil},
  {city: "Zagreb", country: "Croatia", state: nil},
  {city: "Zurich", country: "Switzerland", state: nil}
])
