Location.create([
  {city: "Abu Dhabi", country: "United Arab Emirates"},
  {city: "Aix-En-Provence", country: "France"},
  {city: "Alicante", country: "Spain"},
  {city: "Amsterdam", country: "The Netherlands"},
  {city: "Athens", country: "Greece"},
  {city: "Atlanta", country: "USA"},
  {city: "Atlantic City", country: "USA"},
  {city: "Austin", country: "USA"},
  {city: "Baltimore", country: "USA"},
  {city: "Bangkok", country: "Thailand"},
  {city: "Barcelona", country: "Spain"},
  {city: "Beijing", country: "China"},
  {city: "Benidorm", country: "Spain"},
  {city: "Bergen", country: "Norway"},
  {city: "Berlin", country: "Germany"},
  {city: "Birmingham", country: "UK"},
  {city: "Bologna", country: "Italy"},
  {city: "Boston", country: "USA"},
  {city: "Brisbane", country: "Australia"},
  {city: "Brussels", country: "Belgium"},
  {city: "Budapest", country: "Hungary"},
  {city: "Buenos Aires", country: "Argentina"},
  {city: "Cairo", country: "Egypt"},
  {city: "Cannes", country: "France"},
  {city: "Cape Town", country: "South Africa"},
  {city: "Chicago", country: "USA"},
  {city: "Cologne", country: "Germany"},
  {city: "Copenhagen", country: "Denmark"},
  {city: "Dallas", country: "USA"},
  {city: "Denver", country: "USA"},
  {city: "Detroit", country: "USA"},
  {city: "Dresden", country: "Germany"},
  {city: "Dubai", country: "United Arab Emirates"},
  {city: "Dublin", country: "UK"},
  {city: "Dubrovnik", country: "Croatia"},
  {city: "Düsseldorf", country: "Germany"},
  {city: "Edinburgh", country: "UK"},
  {city: "Florence", country: "Italy"},
  {city: "Fort Lauderdale", country: "US"},
  {city: "Frankfurt", country: "Germany"},
  {city: "Fuerteventura", country: "Spain"},
  {city: "Geneva", country: "Switzerland"},
  {city: "Glasgow", country: "UK"},
  {city: "Gothenburg", country: "Sweden"},
  {city: "Gran Canaria", country: "Spain"},
  {city: "Granada", country: "Spain"},
  {city: "Hamburg", country: "Germany"},
  {city: "Hanoi", country: "Vietnam"},
  {city: "Havana", country: "Cuba"},
  {city: "Helsinki", country: "Finland"},
  {city: "Hong Kong", country: "China"},
  {city: "Honolulu", country: "USA"},
  {city: "Houston", country: "USA"},
  {city: "Indianapolis", country: "USA"},
  {city: "Istanbul", country: "Turkey"},
  {city: "Kansas City", country: "USA"},
  {city: "Krakow", country: "Poland"},
  {city: "Kuala Lumpur", country: "Malaysia"},
  {city: "Kyoto", country: "Japan"},
  {city: "Lake Tahoe", country: "USA"},
  {city: "Lanzarote", country: "Spain"},
  {city: "Las Vegas", country: "USA"},
  {city: "Leipzig", country: "Germany"},
  {city: "Lisbon", country: "Portugal"},
  {city: "Liverpool", country: "UK"},
  {city: "London", country: "UK"},
  {city: "Los Angeles", country: "US"},
  {city: "Luxembourg"},
  {city: "Lyon", country: "France"},
  {city: "Madrid", country: "Spain"},
  {city: "Málaga", country: "Spain"},
  {city: "Malmo", country: "Sweden"},
  {city: "Manchester", country: "UK"},
  {city: "Marbella", country: "Spain"},
  {city: "Marrakech", country: "Morocco"},
  {city: "Marseille", country: "France"},
  {city: "Melbourne", country: "Australia"},
  {city: "Messina", country: "Italy"},
  {city: "Mexico City", country: "Mexico"},
  {city: "Miami", country: "USA"},
  {city: "Milan", country: "Italy"},
  {city: "Minneapolis", country: "USA"},
  {city: "Monte Carlo", country: "Monaco"},
  {city: "Montreal", country: "Canada"},
  {city: "Moscow", country: "Russia"},
  {city: "Mumbai", country: "India"},
  {city: "Munich", country: "Germany"},
  {city: "Napa Valley", country: "USA"},
  {city: "Naples", country: "Italy"},
  {city: "Nashville", country: "USA"},
  {city: "New Orleans", country: "USA"},
  {city: "New York", country: "USA"},
  {city: "Nice", country: "France"},
  {city: "Oakland", country: "USA"},
  {city: "Orlando", country: "USA"},
  {city: "Oslo", country: "Norway"},
  {city: "Palermo", country: "Italy"},
  {city: "Paris", country: "France"},
  {city: "Parma", country: "Italy"},
  {city: "Philadelphia", country: "USA"},
  {city: "Phoenix", country: "USA"},
  {city: "Pisa", country: "Italy"},
  {city: "Portland", country: "USA"},
  {city: "Prague", country: "Czech Republic"},
  {city: "Reykjavik", country: "Iceland"},
  {city: "Riga", country: "Latvia"},
  {city: "Rio de Janeiro", country: "Brazil"},
  {city: "Rome", country: "Italy"},
  {city: "Sacramento", country: "USA"},
  {city: "Salt Lake City", country: "USA"},
  {city: "Salzburg", country: "Austria"},
  {city: "San Antonio", country: "USA"},
  {city: "San Diego", country: "USA"},
  {city: "San Francisco", country: "USA"},
  {city: "San Jose", country: "USA"},
  {city: "San Sebastián", country: "Spain"},
  {city: "Santa Barbara", country: "USA"},
  {city: "São Paulo", country: "Brazil"},
  {city: "Sardinia", country: "Italy"},
  {city: "Savannah", country: "USA"},
  {city: "Seattle", country: "USA"},
  {city: "Seoul", country: "Korea"},
  {city: "Seville", country: "Spain"},
  {city: "Shanghai", country: "China"},
  {city: "Siena", country: "Italy"},
  {city: "Singapore"},
  {city: "Siracusa", country: "Rome"},
  {city: "Sochi", country: "Russia"},
  {city: "St. Louis", country: "USA"},
  {city: "St. Petersburg", country: "Russia"},
  {city: "Stockholm", country: "Sweden"},
  {city: "Stuttgart", country: "Germany"},
  {city: "Sydney", country: "Australia"},
  {city: "Tallinn", country: "Estonia"},
  {city: "Tampa", country: "USA"},
  {city: "Tenerife", country: "Spain"},
  {city: "Tokyo", country: "Japan"},
  {city: "Toronto", country: "Canada"},
  {city: "Turin", country: "Italy"},
  {city: "Valencia", country: "Spain"},
  {city: "Vancouver", country: "Canada"},
  {city: "Venice", country: "Italy"},
  {city: "Verona", country: "Italy"},
  {city: "Vienna", country: "Austria"},
  {city: "Warsaw", country: "Poland"},
  {city: "Washington", country: "US"},
  {city: "Zagreb", country: "Croatia"},
  {city: "Zurich", country: "Switzerland"}
])